require(ggplot2)
require(gridExtra)
#replace wmtMoves with path to output csv generated by SparkEarningsAnalysis
df= read.csv("E:\\wmtMoves.csv",colClasses = c("integer","Date","Date","Date","numeric","Date","Date","numeric"))
df$relDate = as.factor( format(df$relDate,"%Y") )
#combine relDate year and qtr into a factor of YEAR-QTR
#df$qtr = as.factor( paste( format(df$relDate,"%Y"),df$qtr,sep="-"))


be <- ggplot(df, aes(x=qtr)) +
  geom_col( aes( y=bMove, fill=relDate ), position = "dodge" ) +
  labs(title="Largest Price Move Before Earnings", x="quarter", y="dollar amount")

ae <- ggplot(df, aes(x=qtr)) +
  geom_col( aes( y=aMove, fill=relDate ), position = "dodge" ) +
  labs(title="Largest Price Move After Earnings", x="quarter", y="dollar amount")

grid.arrange(be, ae, ncol=2)